### ISSUE TITLE
Is the bundler dependency needed in the gemspec?

### ISSUE THREAD

**Issue by karl-petter** [scrapper/fit4ruby#1]
Hi,

I found your lib for a project that I'm working on, http://www.peppster.com. I think it can be quite useful and we are happy to help out improving and contribute with any changes. One thing I noted was that in the gemspec file, you have included a dependency to bundler. And for version 1.6. Any specific reason?

I encountered this problem when I ran bundle install:

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.6.4)

  Current Bundler version:
    bundler (1.12.5)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.6.4)' in any of the sources
```

**Comment by scrapper** [comment]
Great to hear! No, there is no specific reason to limit bundler to 1.6.x.  I'll change it to >=1.6.4 since that's the earliest version that I've tested.
