### ISSUE TITLE
error when importing - Stryd related

### ISSUE THREAD

**Issue by davidwul** [scrapper/fit4ruby#11]
Since I added the Stryd footpod, postrunner trigger a bug, I guess it's in fit4ruby.
I tried to run the master branch, without any more luck.

Any idea? the error is below;
ERROR: Rename field 'offset' in BinData::Struct, as it shadows an existing method.
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/struct.rb:387:in `block in ensure_field_names_are_valid'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/struct.rb:385:in `each'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/struct.rb:385:in `ensure_field_names_are_valid'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/struct.rb:361:in `sanitize_fields'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/struct.rb:336:in `sanitize_parameters!'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/sanitize.rb:278:in `sanitize!'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/sanitize.rb:197:in `initialize'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/sanitize.rb:186:in `new'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/sanitize.rb:186:in `sanitize'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/base.rb:279:in `extract_args'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/base.rb:249:in `extract_args'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/base.rb:80:in `initialize'
/var/lib/gems/2.3.0/gems/bindata-2.1.0/lib/bindata/warnings.rb:22:in `initialize_with_warning'
/var/lib/gems/2.3.0/gems/fit4ruby-1.6.1/lib/fit4ruby/FitMessageRecord.rb:164:in `new'
/var/lib/gems/2.3.0/gems/fit4ruby-1.6.1/lib/fit4ruby/FitMessageRecord.rb:164:in `produce'
/var/lib/gems/2.3.0/gems/fit4ruby-1.6.1/lib/fit4ruby/FitMessageRecord.rb:41:in `initialize'
/var/lib/gems/2.3.0/gems/fit4ruby-1.6.1/lib/fit4ruby/FitRecord.rb:49:in `new'
/var/lib/gems/2.3.0/gems/fit4ruby-1.6.1/lib/fit4ruby/FitRecord.rb:49:in `read'
/var/lib/gems/2.3.0/gems/fit4ruby-1.6.1/lib/fit4ruby/FitFile.rb:59:in `read'
/var/lib/gems/2.3.0/gems/fit4ruby-1.6.1/lib/fit4ruby.rb:18:in `read'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/lib/postrunner/Main.rb:476:in `import_fit_file'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/lib/postrunner/Main.rb:464:in `process_file'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/lib/postrunner/Main.rb:449:in `block in process_files'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/lib/postrunner/Main.rb:443:in `each'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/lib/postrunner/Main.rb:443:in `process_files'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/lib/postrunner/Main.rb:347:in `execute_command'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/lib/postrunner/Main.rb:77:in `main'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/lib/postrunner.rb:24:in `<module:PostRunner>'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/lib/postrunner.rb:22:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/postrunner-0.8.1/bin/postrunner:4:in `<top (required)>'
/usr/local/bin/postrunner:22:in `load'
/usr/local/bin/postrunner:22:in `<main>'

*******************************************************************************
You have triggered a bug in PostRunner 0.8.1!

**Comment by scrapper** [comment]
This looks like a compatibility issue with BinData. Can you try BinData 
version 2.3.0, please?

Chris

**Comment by davidwul** [comment]
:+1: 
Working with 2.3.0, but not with 2.4.1

Thanks for the quick reply
