### ISSUE TITLE
Record message num 87 is stroke_distance

### ISSUE THREAD

**Issue by Abasz** [scrapper/fit4ruby#24]
Num 87 in the record message is actually stroke_distance

https://github.com/scrapper/fit4ruby/blob/647cad8430ba9228b580504d97e3fe3eb85ccddd/lib/fit4ruby/GlobalFitMessages.rb#L645

<table border=1 class="table table-striped table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">Message Name</th>
<th title="Field #2">Field Def #</th>
<th title="Field #3">Field Name</th>
<th title="Field #4">Field Type</th>
<th title="Field #5">Array</th>
<th title="Field #6">Components</th>
<th title="Field #7">Scale</th>
<th title="Field #8">Offset</th>
<th title="Field #9">Units</th>
<th title="Field #10">Bits</th>
<th title="Field #11">Accumulate</th>
<th title="Field #12">Ref Field Name</th>
<th title="Field #13">Ref Field Value</th>
<th title="Field #14">Comment</th>
<th title="Field #15">Products:</th>
<th title="Field #16">EXAMPLE</th>
</tr></thead>
<tbody><tr><td>record</td>
<td align="right"></td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td align="right"></td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
</tr>
<tr><td> </td>
<td align="right">87</td>
<td>stroke_distance</td>
<td>uint16</td>
<td> </td>
<td> </td>
<td align="right">100</td>
<td> </td>
<td>m</td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
</tr>
</tbody></table>
</div></div></div>

**Comment by scrapper** [comment]
Thanks for the hint! Updated.

**Comment by Abasz** [comment]
there is word from garmin on this topic
https://forums.garmin.com/developer/fit-sdk/f/discussion/323579/missing-stroke_distance-field-on-the-record-message/1586198#1586198

They intend to add the field to the official SDK, but name it differently (IMHO their naming is inconsistent with the session and lap but this is garmin... :))
