### ISSUE TITLE
NaN issue when importing from a gpx

### ISSUE THREAD

**Issue by davidwul** [scrapper/fit4ruby#7]
Hi I'm pursuing the import from gpx feature. 
It's starting to give some results. I have a problem with Nan value.
 /var/lib/gems/2.3.0/gems/fit4ruby-1.4.0/lib/fit4ruby/GlobalFitMessage.rb:121:in `to_i': NaN (FloatDomainError)
I'm not sure why and what is happening. I want to ask your expertise about if [my fix](https://github.com/davidwul/fit4ruby/commit/c13a939be556d504af0714f7614c50d77417e912) makes sense? Or should I understand why these NaN values appears?
Thanks for your comments.

**Comment by scrapper** [comment]
That fix is just a workaround for your specific problem. Somehow you have assigned a NaN value (usually a division by 0 result) into the Fit4Ruby data structures. There is little to no sanity checking right now when you create your own fit file. As the FIT file is strongly typed, it would make sense to add some checking when values are passed during FIT message creation.
