### ISSUE TITLE
Undefined method top_level_record

### ISSUE THREAD

**Issue by wolli2710** [scrapper/fit4ruby#8]
I receive the following error when reading files that are of a short duration:
NoMethodError: undefined method `top_level_record' for nil:NilClass

The gem works really good for normal runs, cycling sessions, triathlons... but it's not working for files with a short duration. My question is now can someone tell me whats the difference between those fit files?

**Comment by scrapper** [comment]
Can you please post the full error message with line numbers and full back-trace?

**Comment by wolli2710** [comment]
I already found the issue. The problem is, that I can't write the string of the affected fit file into a file with proper ruby methods. The content of the file is then always empty, which leads to the reported error. My question now is would it be possible to have a method without a filehandling at all? I saw you are using bindata so I guess it would be hard to have sth. like read_from_string(str) ?
